name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and set up Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Add Poetry to PATH for Windows
      run: echo "##[add-path]%USERPROFILE%\.poetry\bin"
      if: matrix.os == 'windows-latest'
    - name: Add Poetry to PATH for Linux
      run: echo "::add-path::$HOME/.poetry/bin"
      if: matrix.os == 'ubuntu-latest'
    - name: Add Poetry to PATH for Mac OS
      run: echo "::add-path::$HOME/.poetry/bin"
      if: matrix.os == 'macos-latest'
    - name: Set Poetry to create virtualenv inside project directory
      run: |
        poetry config virtualenvs.in-project true
    - name: Set up cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Test
      run: |
        poetry run test
    - name: Build
      run: |
        poetry run pyinstaller --onefile --windowed inbac/inbac.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
          name: inbac-${{ runner.os }}
          path: dist
